# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-12 20:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='会议主题')),
                ('start', models.DateTimeField(verbose_name='开始时间')),
                ('end', models.DateTimeField(verbose_name='结束时间')),
                ('remark', models.TextField(blank=True, max_length=500, null=True, verbose_name='会议备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '预定会议',
                'verbose_name_plural': '预定会议列表',
            },
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='会议室名称')),
                ('address', models.CharField(max_length=30, verbose_name='会议室地点')),
                ('space', models.IntegerField(default=0, verbose_name='可容纳人数')),
                ('chamber_img', models.ImageField(blank=True, default='/chamber_img/default_chamber_img.jpg', null=True, upload_to=user.models.upload_image_chamber, verbose_name='会议室图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '会议室',
                'verbose_name_plural': '会议室列表',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='设备名称')),
                ('num', models.IntegerField(default=0, verbose_name='设备数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备列表',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='消息主题')),
                ('meeting', models.CharField(max_length=20, verbose_name='会议ID')),
                ('content', models.CharField(max_length=255, verbose_name='消息')),
                ('status', models.IntegerField(choices=[(1, '更新状态'), (0, '首次创建'), (-1, '对应会议被删除')], default=0, verbose_name='本条消息是否过期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户消息',
                'verbose_name_plural': '用户消息',
            },
        ),
        migrations.CreateModel(
            name='SepVoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voices_file', models.FileField(upload_to=user.models.upload_voices_file, verbose_name='音频文件')),
                ('result', models.TextField(default='等待转写文字中...', verbose_name='语音转录的文字')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '语音转写-人声分离',
                'verbose_name_plural': '语音转写-人声分离',
            },
        ),
        migrations.CreateModel(
            name='Signed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '参会人员签到表',
                'verbose_name_plural': '参会人员签到表',
            },
        ),
        migrations.CreateModel(
            name='UserUploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='上传的文件', upload_to=user.models.upload_file, verbose_name='上传的文件')),
                ('file_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='文件名字')),
                ('file_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='文件大小')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chamber.ApplyMeeting', verbose_name='对应会议')),
            ],
            options={
                'verbose_name': '用户上传的文件',
                'verbose_name_plural': '用户上传的文件',
            },
        ),
    ]
