# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-12 20:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chamber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useruploadfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传的用户'),
        ),
        migrations.AddField(
            model_name='signed',
            name='meeting',
            field=models.ForeignKey(db_column='meeting', on_delete=django.db.models.deletion.CASCADE, to='chamber.ApplyMeeting', verbose_name='会议ID'),
        ),
        migrations.AddField(
            model_name='signed',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收消息的用户'),
        ),
        migrations.AddField(
            model_name='sepvoices',
            name='meeting',
            field=models.ForeignKey(db_column='meeting', on_delete=django.db.models.deletion.CASCADE, to='chamber.ApplyMeeting', verbose_name='对应会议'),
        ),
        migrations.AddField(
            model_name='sepvoices',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传的用户'),
        ),
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收消息的用户'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, to='chamber.Equipment', verbose_name='所拥有设备'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='host',
            field=models.ForeignKey(db_column='host', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='applymeeting',
            name='chamber',
            field=models.ForeignKey(db_column='chamber', on_delete=django.db.models.deletion.CASCADE, to='chamber.Chamber', verbose_name='会议室'),
        ),
        migrations.AddField(
            model_name='applymeeting',
            name='joins',
            field=models.ManyToManyField(related_query_name='join_user', to=settings.AUTH_USER_MODEL, verbose_name='参与人'),
        ),
        migrations.AddField(
            model_name='applymeeting',
            name='pubuser',
            field=models.ForeignKey(db_column='pubuser', on_delete=django.db.models.deletion.CASCADE, related_name='pub_user', to=settings.AUTH_USER_MODEL, verbose_name='会议发起人'),
        ),
        migrations.AddField(
            model_name='applymeeting',
            name='speaker',
            field=models.ForeignKey(db_column='speaker', on_delete=django.db.models.deletion.CASCADE, related_name='speaker_user', to=settings.AUTH_USER_MODEL, verbose_name='主讲人'),
        ),
    ]
